export default {
  products: [
    {
      _id: "1",
      name: "White Shirt",
      category: "Shirts",
      image: "/images/whiteshirt.jpg",
      price: 200,
      brand: "Gucci",
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
    },
    {
      _id: "2",
      name: "Oversized Sweater",
      category: "Sweaters",
      image: "/images/whitesweater.jpg",
      price: 60,
      brand: "Zara",
      rating: 4.5,
      numReviews: 15,
      countInStock: 50,
    },
    {
      _id: "3",
      name: "Leggings",
      category: "Athletic",
      image: "/images/pants.jpg",
      price: 60,
      brand: "Lululemon",
      rating: 4.0,
      numReviews: 1,
      countInStock: 0,
    },

    {
      _id: "4",
      name: "Suede Coat",
      category: "Coat",
      image: "/images/coat.jpg",
      price: 140,
      brand: "Banana Republic",
      rating: 3.0,
      numReviews: 1,
      countInStock: 2,
    },
  ],
};
